name = "IrisCore"
uuid = "8494a7e0-3192-4b7a-a864-04ad2416ac01"
authors = ["Phelipe Wesley <phelipewesleydeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"

[compat]
DecisionTree = "= 0.10.1"
MLJ = "= 0.11.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
